trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# ---------------- BUILD STAGE ----------------
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Starting Build..."
      displayName: 'Start Build'

    - script: |
        echo "Compiling code..."
        echo "Build successful"
      displayName: 'Build Application'


# ---------------- TEST STAGE ----------------
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - script: echo "Starting Tests..."
      displayName: 'Start Testing'

    - script: |
        echo "Running test cases..."
        echo "All tests passed"
